/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1Status;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoArgoprojEventsV1alpha1SensorStatus
 */
public class IoArgoprojEventsV1alpha1SensorStatusTest {
    private final IoArgoprojEventsV1alpha1SensorStatus model = new IoArgoprojEventsV1alpha1SensorStatus();

    /**
     * Model tests for IoArgoprojEventsV1alpha1SensorStatus
     */
    @Test
    public void testIoArgoprojEventsV1alpha1SensorStatus() {
        // TODO: test IoArgoprojEventsV1alpha1SensorStatus
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
