/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.IoK8sApiCoreV1ServicePort;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoArgoprojEventsV1alpha1Service
 */
public class IoArgoprojEventsV1alpha1ServiceTest {
    private final IoArgoprojEventsV1alpha1Service model = new IoArgoprojEventsV1alpha1Service();

    /**
     * Model tests for IoArgoprojEventsV1alpha1Service
     */
    @Test
    public void testIoArgoprojEventsV1alpha1Service() {
        // TODO: test IoArgoprojEventsV1alpha1Service
    }

    /**
     * Test the property 'clusterIP'
     */
    @Test
    public void clusterIPTest() {
        // TODO: test clusterIP
    }

    /**
     * Test the property 'ports'
     */
    @Test
    public void portsTest() {
        // TODO: test ports
    }

}
