/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1AMQPEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1AzureEventsHubEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1AzureQueueStorageEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1AzureServiceBusEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1BitbucketEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1BitbucketServerEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1CalendarEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1EmitterEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1FileEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1GenericEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1GerritEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1GithubEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1GitlabEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1HDFSEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1KafkaEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1MQTTEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1NATSEventsSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1NSQEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1PubSubEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1PulsarEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1RedisEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1RedisStreamEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1ResourceEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1S3Artifact;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1SFTPEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1SNSEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1SQSEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1Service;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1SlackEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1StorageGridEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1StripeEventSource;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1Template;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1WebhookEventSource;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoArgoprojEventsV1alpha1EventSourceSpec
 */
public class IoArgoprojEventsV1alpha1EventSourceSpecTest {
    private final IoArgoprojEventsV1alpha1EventSourceSpec model = new IoArgoprojEventsV1alpha1EventSourceSpec();

    /**
     * Model tests for IoArgoprojEventsV1alpha1EventSourceSpec
     */
    @Test
    public void testIoArgoprojEventsV1alpha1EventSourceSpec() {
        // TODO: test IoArgoprojEventsV1alpha1EventSourceSpec
    }

    /**
     * Test the property 'amqp'
     */
    @Test
    public void amqpTest() {
        // TODO: test amqp
    }

    /**
     * Test the property 'azureEventsHub'
     */
    @Test
    public void azureEventsHubTest() {
        // TODO: test azureEventsHub
    }

    /**
     * Test the property 'azureQueueStorage'
     */
    @Test
    public void azureQueueStorageTest() {
        // TODO: test azureQueueStorage
    }

    /**
     * Test the property 'azureServiceBus'
     */
    @Test
    public void azureServiceBusTest() {
        // TODO: test azureServiceBus
    }

    /**
     * Test the property 'bitbucket'
     */
    @Test
    public void bitbucketTest() {
        // TODO: test bitbucket
    }

    /**
     * Test the property 'bitbucketserver'
     */
    @Test
    public void bitbucketserverTest() {
        // TODO: test bitbucketserver
    }

    /**
     * Test the property 'calendar'
     */
    @Test
    public void calendarTest() {
        // TODO: test calendar
    }

    /**
     * Test the property 'emitter'
     */
    @Test
    public void emitterTest() {
        // TODO: test emitter
    }

    /**
     * Test the property 'eventBusName'
     */
    @Test
    public void eventBusNameTest() {
        // TODO: test eventBusName
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'generic'
     */
    @Test
    public void genericTest() {
        // TODO: test generic
    }

    /**
     * Test the property 'gerrit'
     */
    @Test
    public void gerritTest() {
        // TODO: test gerrit
    }

    /**
     * Test the property 'github'
     */
    @Test
    public void githubTest() {
        // TODO: test github
    }

    /**
     * Test the property 'gitlab'
     */
    @Test
    public void gitlabTest() {
        // TODO: test gitlab
    }

    /**
     * Test the property 'hdfs'
     */
    @Test
    public void hdfsTest() {
        // TODO: test hdfs
    }

    /**
     * Test the property 'kafka'
     */
    @Test
    public void kafkaTest() {
        // TODO: test kafka
    }

    /**
     * Test the property 'minio'
     */
    @Test
    public void minioTest() {
        // TODO: test minio
    }

    /**
     * Test the property 'mqtt'
     */
    @Test
    public void mqttTest() {
        // TODO: test mqtt
    }

    /**
     * Test the property 'nats'
     */
    @Test
    public void natsTest() {
        // TODO: test nats
    }

    /**
     * Test the property 'nsq'
     */
    @Test
    public void nsqTest() {
        // TODO: test nsq
    }

    /**
     * Test the property 'pubSub'
     */
    @Test
    public void pubSubTest() {
        // TODO: test pubSub
    }

    /**
     * Test the property 'pulsar'
     */
    @Test
    public void pulsarTest() {
        // TODO: test pulsar
    }

    /**
     * Test the property 'redis'
     */
    @Test
    public void redisTest() {
        // TODO: test redis
    }

    /**
     * Test the property 'redisStream'
     */
    @Test
    public void redisStreamTest() {
        // TODO: test redisStream
    }

    /**
     * Test the property 'replicas'
     */
    @Test
    public void replicasTest() {
        // TODO: test replicas
    }

    /**
     * Test the property 'resource'
     */
    @Test
    public void resourceTest() {
        // TODO: test resource
    }

    /**
     * Test the property 'service'
     */
    @Test
    public void serviceTest() {
        // TODO: test service
    }

    /**
     * Test the property 'sftp'
     */
    @Test
    public void sftpTest() {
        // TODO: test sftp
    }

    /**
     * Test the property 'slack'
     */
    @Test
    public void slackTest() {
        // TODO: test slack
    }

    /**
     * Test the property 'sns'
     */
    @Test
    public void snsTest() {
        // TODO: test sns
    }

    /**
     * Test the property 'sqs'
     */
    @Test
    public void sqsTest() {
        // TODO: test sqs
    }

    /**
     * Test the property 'storageGrid'
     */
    @Test
    public void storageGridTest() {
        // TODO: test storageGrid
    }

    /**
     * Test the property 'stripe'
     */
    @Test
    public void stripeTest() {
        // TODO: test stripe
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'webhook'
     */
    @Test
    public void webhookTest() {
        // TODO: test webhook
    }

}
