/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1ArtifactoryArtifactRepository;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1AzureArtifactRepository;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1GCSArtifactRepository;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1HDFSArtifactRepository;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1OSSArtifactRepository;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1S3ArtifactRepository;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoArgoprojWorkflowV1alpha1ArtifactRepository
 */
public class IoArgoprojWorkflowV1alpha1ArtifactRepositoryTest {
    private final IoArgoprojWorkflowV1alpha1ArtifactRepository model = new IoArgoprojWorkflowV1alpha1ArtifactRepository();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1ArtifactRepository
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1ArtifactRepository() {
        // TODO: test IoArgoprojWorkflowV1alpha1ArtifactRepository
    }

    /**
     * Test the property 'archiveLogs'
     */
    @Test
    public void archiveLogsTest() {
        // TODO: test archiveLogs
    }

    /**
     * Test the property 'artifactory'
     */
    @Test
    public void artifactoryTest() {
        // TODO: test artifactory
    }

    /**
     * Test the property 'azure'
     */
    @Test
    public void azureTest() {
        // TODO: test azure
    }

    /**
     * Test the property 'gcs'
     */
    @Test
    public void gcsTest() {
        // TODO: test gcs
    }

    /**
     * Test the property 'hdfs'
     */
    @Test
    public void hdfsTest() {
        // TODO: test hdfs
    }

    /**
     * Test the property 'oss'
     */
    @Test
    public void ossTest() {
        // TODO: test oss
    }

    /**
     * Test the property 's3'
     */
    @Test
    public void s3Test() {
        // TODO: test s3
    }

}
