/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1DataSource;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1TransformationStep;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoArgoprojWorkflowV1alpha1Data
 */
public class IoArgoprojWorkflowV1alpha1DataTest {
    private final IoArgoprojWorkflowV1alpha1Data model = new IoArgoprojWorkflowV1alpha1Data();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1Data
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1Data() {
        // TODO: test IoArgoprojWorkflowV1alpha1Data
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'transformation'
     */
    @Test
    public void transformationTest() {
        // TODO: test transformation
    }

}
