/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1CatchupConfiguration;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1ConfigMapPersistence;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoArgoprojEventsV1alpha1EventPersistence
 */
public class IoArgoprojEventsV1alpha1EventPersistenceTest {
    private final IoArgoprojEventsV1alpha1EventPersistence model = new IoArgoprojEventsV1alpha1EventPersistence();

    /**
     * Model tests for IoArgoprojEventsV1alpha1EventPersistence
     */
    @Test
    public void testIoArgoprojEventsV1alpha1EventPersistence() {
        // TODO: test IoArgoprojEventsV1alpha1EventPersistence
    }

    /**
     * Test the property 'catchup'
     */
    @Test
    public void catchupTest() {
        // TODO: test catchup
    }

    /**
     * Test the property 'configMap'
     */
    @Test
    public void configMapTest() {
        // TODO: test configMap
    }

}
