/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Artifact;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoArgoprojWorkflowV1alpha1ManifestFrom
 */
public class IoArgoprojWorkflowV1alpha1ManifestFromTest {
    private final IoArgoprojWorkflowV1alpha1ManifestFrom model = new IoArgoprojWorkflowV1alpha1ManifestFrom();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1ManifestFrom
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1ManifestFrom() {
        // TODO: test IoArgoprojWorkflowV1alpha1ManifestFrom
    }

    /**
     * Test the property 'artifact'
     */
    @Test
    public void artifactTest() {
        // TODO: test artifact
    }

}
