/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoK8sApiCoreV1VolumeResourceRequirements
 */
public class IoK8sApiCoreV1VolumeResourceRequirementsTest {
    private final IoK8sApiCoreV1VolumeResourceRequirements model = new IoK8sApiCoreV1VolumeResourceRequirements();

    /**
     * Model tests for IoK8sApiCoreV1VolumeResourceRequirements
     */
    @Test
    public void testIoK8sApiCoreV1VolumeResourceRequirements() {
        // TODO: test IoK8sApiCoreV1VolumeResourceRequirements
    }

    /**
     * Test the property 'limits'
     */
    @Test
    public void limitsTest() {
        // TODO: test limits
    }

    /**
     * Test the property 'requests'
     */
    @Test
    public void requestsTest() {
        // TODO: test requests
    }

}
