/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoK8sApiCoreV1AppArmorProfile
 */
public class IoK8sApiCoreV1AppArmorProfileTest {
    private final IoK8sApiCoreV1AppArmorProfile model = new IoK8sApiCoreV1AppArmorProfile();

    /**
     * Model tests for IoK8sApiCoreV1AppArmorProfile
     */
    @Test
    public void testIoK8sApiCoreV1AppArmorProfile() {
        // TODO: test IoK8sApiCoreV1AppArmorProfile
    }

    /**
     * Test the property 'localhostProfile'
     */
    @Test
    public void localhostProfileTest() {
        // TODO: test localhostProfile
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
