/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.IoK8sApimachineryPkgApisMetaV1LabelSelector;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoK8sApiCoreV1PodAffinityTerm
 */
public class IoK8sApiCoreV1PodAffinityTermTest {
    private final IoK8sApiCoreV1PodAffinityTerm model = new IoK8sApiCoreV1PodAffinityTerm();

    /**
     * Model tests for IoK8sApiCoreV1PodAffinityTerm
     */
    @Test
    public void testIoK8sApiCoreV1PodAffinityTerm() {
        // TODO: test IoK8sApiCoreV1PodAffinityTerm
    }

    /**
     * Test the property 'labelSelector'
     */
    @Test
    public void labelSelectorTest() {
        // TODO: test labelSelector
    }

    /**
     * Test the property 'matchLabelKeys'
     */
    @Test
    public void matchLabelKeysTest() {
        // TODO: test matchLabelKeys
    }

    /**
     * Test the property 'mismatchLabelKeys'
     */
    @Test
    public void mismatchLabelKeysTest() {
        // TODO: test mismatchLabelKeys
    }

    /**
     * Test the property 'namespaceSelector'
     */
    @Test
    public void namespaceSelectorTest() {
        // TODO: test namespaceSelector
    }

    /**
     * Test the property 'namespaces'
     */
    @Test
    public void namespacesTest() {
        // TODO: test namespaces
    }

    /**
     * Test the property 'topologyKey'
     */
    @Test
    public void topologyKeyTest() {
        // TODO: test topologyKey
    }

}
