/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoK8sApiCoreV1FlockerVolumeSource
 */
public class IoK8sApiCoreV1FlockerVolumeSourceTest {
    private final IoK8sApiCoreV1FlockerVolumeSource model = new IoK8sApiCoreV1FlockerVolumeSource();

    /**
     * Model tests for IoK8sApiCoreV1FlockerVolumeSource
     */
    @Test
    public void testIoK8sApiCoreV1FlockerVolumeSource() {
        // TODO: test IoK8sApiCoreV1FlockerVolumeSource
    }

    /**
     * Test the property 'datasetName'
     */
    @Test
    public void datasetNameTest() {
        // TODO: test datasetName
    }

    /**
     * Test the property 'datasetUUID'
     */
    @Test
    public void datasetUUIDTest() {
        // TODO: test datasetUUID
    }

}
