/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IoK8sApiCoreV1ObjectFieldSelector;
import org.openapitools.client.model.IoK8sApiCoreV1ResourceFieldSelector;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IoK8sApiCoreV1DownwardAPIVolumeFile
 */
public class IoK8sApiCoreV1DownwardAPIVolumeFileTest {
    private final IoK8sApiCoreV1DownwardAPIVolumeFile model = new IoK8sApiCoreV1DownwardAPIVolumeFile();

    /**
     * Model tests for IoK8sApiCoreV1DownwardAPIVolumeFile
     */
    @Test
    public void testIoK8sApiCoreV1DownwardAPIVolumeFile() {
        // TODO: test IoK8sApiCoreV1DownwardAPIVolumeFile
    }

    /**
     * Test the property 'fieldRef'
     */
    @Test
    public void fieldRefTest() {
        // TODO: test fieldRef
    }

    /**
     * Test the property 'mode'
     */
    @Test
    public void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'resourceFieldRef'
     */
    @Test
    public void resourceFieldRefTest() {
        // TODO: test resourceFieldRef
    }

}
