/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IoK8sApiCoreV1SecretKeySelector;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * IoArgoprojEventsV1alpha1SASLConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-24T03:51:41.763920791Z[Etc/UTC]", comments = "Generator version: 7.12.0-SNAPSHOT")
public class IoArgoprojEventsV1alpha1SASLConfig {
  public static final String SERIALIZED_NAME_MECHANISM = "mechanism";
  @SerializedName(SERIALIZED_NAME_MECHANISM)
  @javax.annotation.Nullable
  private String mechanism;

  public static final String SERIALIZED_NAME_PASSWORD_SECRET = "passwordSecret";
  @SerializedName(SERIALIZED_NAME_PASSWORD_SECRET)
  @javax.annotation.Nullable
  private IoK8sApiCoreV1SecretKeySelector passwordSecret;

  public static final String SERIALIZED_NAME_USER_SECRET = "userSecret";
  @SerializedName(SERIALIZED_NAME_USER_SECRET)
  @javax.annotation.Nullable
  private IoK8sApiCoreV1SecretKeySelector userSecret;

  public IoArgoprojEventsV1alpha1SASLConfig() {
  }

  public IoArgoprojEventsV1alpha1SASLConfig mechanism(@javax.annotation.Nullable String mechanism) {
    this.mechanism = mechanism;
    return this;
  }

  /**
   * Get mechanism
   * @return mechanism
   */
  @javax.annotation.Nullable
  public String getMechanism() {
    return mechanism;
  }

  public void setMechanism(@javax.annotation.Nullable String mechanism) {
    this.mechanism = mechanism;
  }


  public IoArgoprojEventsV1alpha1SASLConfig passwordSecret(@javax.annotation.Nullable IoK8sApiCoreV1SecretKeySelector passwordSecret) {
    this.passwordSecret = passwordSecret;
    return this;
  }

  /**
   * Get passwordSecret
   * @return passwordSecret
   */
  @javax.annotation.Nullable
  public IoK8sApiCoreV1SecretKeySelector getPasswordSecret() {
    return passwordSecret;
  }

  public void setPasswordSecret(@javax.annotation.Nullable IoK8sApiCoreV1SecretKeySelector passwordSecret) {
    this.passwordSecret = passwordSecret;
  }


  public IoArgoprojEventsV1alpha1SASLConfig userSecret(@javax.annotation.Nullable IoK8sApiCoreV1SecretKeySelector userSecret) {
    this.userSecret = userSecret;
    return this;
  }

  /**
   * Get userSecret
   * @return userSecret
   */
  @javax.annotation.Nullable
  public IoK8sApiCoreV1SecretKeySelector getUserSecret() {
    return userSecret;
  }

  public void setUserSecret(@javax.annotation.Nullable IoK8sApiCoreV1SecretKeySelector userSecret) {
    this.userSecret = userSecret;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojEventsV1alpha1SASLConfig ioArgoprojEventsV1alpha1SASLConfig = (IoArgoprojEventsV1alpha1SASLConfig) o;
    return Objects.equals(this.mechanism, ioArgoprojEventsV1alpha1SASLConfig.mechanism) &&
        Objects.equals(this.passwordSecret, ioArgoprojEventsV1alpha1SASLConfig.passwordSecret) &&
        Objects.equals(this.userSecret, ioArgoprojEventsV1alpha1SASLConfig.userSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mechanism, passwordSecret, userSecret);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojEventsV1alpha1SASLConfig {\n");
    sb.append("    mechanism: ").append(toIndentedString(mechanism)).append("\n");
    sb.append("    passwordSecret: ").append(toIndentedString(passwordSecret)).append("\n");
    sb.append("    userSecret: ").append(toIndentedString(userSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("mechanism");
    openapiFields.add("passwordSecret");
    openapiFields.add("userSecret");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IoArgoprojEventsV1alpha1SASLConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IoArgoprojEventsV1alpha1SASLConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IoArgoprojEventsV1alpha1SASLConfig is not found in the empty JSON string", IoArgoprojEventsV1alpha1SASLConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IoArgoprojEventsV1alpha1SASLConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IoArgoprojEventsV1alpha1SASLConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("mechanism") != null && !jsonObj.get("mechanism").isJsonNull()) && !jsonObj.get("mechanism").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mechanism` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mechanism").toString()));
      }
      // validate the optional field `passwordSecret`
      if (jsonObj.get("passwordSecret") != null && !jsonObj.get("passwordSecret").isJsonNull()) {
        IoK8sApiCoreV1SecretKeySelector.validateJsonElement(jsonObj.get("passwordSecret"));
      }
      // validate the optional field `userSecret`
      if (jsonObj.get("userSecret") != null && !jsonObj.get("userSecret").isJsonNull()) {
        IoK8sApiCoreV1SecretKeySelector.validateJsonElement(jsonObj.get("userSecret"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IoArgoprojEventsV1alpha1SASLConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IoArgoprojEventsV1alpha1SASLConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IoArgoprojEventsV1alpha1SASLConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IoArgoprojEventsV1alpha1SASLConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<IoArgoprojEventsV1alpha1SASLConfig>() {
           @Override
           public void write(JsonWriter out, IoArgoprojEventsV1alpha1SASLConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IoArgoprojEventsV1alpha1SASLConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IoArgoprojEventsV1alpha1SASLConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IoArgoprojEventsV1alpha1SASLConfig
   * @throws IOException if the JSON string is invalid with respect to IoArgoprojEventsV1alpha1SASLConfig
   */
  public static IoArgoprojEventsV1alpha1SASLConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IoArgoprojEventsV1alpha1SASLConfig.class);
  }

  /**
   * Convert an instance of IoArgoprojEventsV1alpha1SASLConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

