/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Backoff is a backoff strategy to use within retryStrategy
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-24T03:51:41.763920791Z[Etc/UTC]", comments = "Generator version: 7.12.0-SNAPSHOT")
public class IoArgoprojWorkflowV1alpha1Backoff {
  public static final String SERIALIZED_NAME_CAP = "cap";
  @SerializedName(SERIALIZED_NAME_CAP)
  @javax.annotation.Nullable
  private String cap;

  public static final String SERIALIZED_NAME_DURATION = "duration";
  @SerializedName(SERIALIZED_NAME_DURATION)
  @javax.annotation.Nullable
  private String duration;

  public static final String SERIALIZED_NAME_FACTOR = "factor";
  @SerializedName(SERIALIZED_NAME_FACTOR)
  @javax.annotation.Nullable
  private String factor;

  public static final String SERIALIZED_NAME_MAX_DURATION = "maxDuration";
  @SerializedName(SERIALIZED_NAME_MAX_DURATION)
  @javax.annotation.Nullable
  private String maxDuration;

  public IoArgoprojWorkflowV1alpha1Backoff() {
  }

  public IoArgoprojWorkflowV1alpha1Backoff cap(@javax.annotation.Nullable String cap) {
    this.cap = cap;
    return this;
  }

  /**
   * Cap is a limit on revised values of the duration parameter. If a multiplication by the factor parameter would make the duration exceed the cap then the duration is set to the cap
   * @return cap
   */
  @javax.annotation.Nullable
  public String getCap() {
    return cap;
  }

  public void setCap(@javax.annotation.Nullable String cap) {
    this.cap = cap;
  }


  public IoArgoprojWorkflowV1alpha1Backoff duration(@javax.annotation.Nullable String duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Duration is the amount to back off. Default unit is seconds, but could also be a duration (e.g. \&quot;2m\&quot;, \&quot;1h\&quot;)
   * @return duration
   */
  @javax.annotation.Nullable
  public String getDuration() {
    return duration;
  }

  public void setDuration(@javax.annotation.Nullable String duration) {
    this.duration = duration;
  }


  public IoArgoprojWorkflowV1alpha1Backoff factor(@javax.annotation.Nullable String factor) {
    this.factor = factor;
    return this;
  }

  /**
   * Get factor
   * @return factor
   */
  @javax.annotation.Nullable
  public String getFactor() {
    return factor;
  }

  public void setFactor(@javax.annotation.Nullable String factor) {
    this.factor = factor;
  }


  public IoArgoprojWorkflowV1alpha1Backoff maxDuration(@javax.annotation.Nullable String maxDuration) {
    this.maxDuration = maxDuration;
    return this;
  }

  /**
   * MaxDuration is the maximum amount of time allowed for a workflow in the backoff strategy. It is important to note that if the workflow template includes activeDeadlineSeconds, the pod&#39;s deadline is initially set with activeDeadlineSeconds. However, when the workflow fails, the pod&#39;s deadline is then overridden by maxDuration. This ensures that the workflow does not exceed the specified maximum duration when retries are involved.
   * @return maxDuration
   */
  @javax.annotation.Nullable
  public String getMaxDuration() {
    return maxDuration;
  }

  public void setMaxDuration(@javax.annotation.Nullable String maxDuration) {
    this.maxDuration = maxDuration;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1Backoff ioArgoprojWorkflowV1alpha1Backoff = (IoArgoprojWorkflowV1alpha1Backoff) o;
    return Objects.equals(this.cap, ioArgoprojWorkflowV1alpha1Backoff.cap) &&
        Objects.equals(this.duration, ioArgoprojWorkflowV1alpha1Backoff.duration) &&
        Objects.equals(this.factor, ioArgoprojWorkflowV1alpha1Backoff.factor) &&
        Objects.equals(this.maxDuration, ioArgoprojWorkflowV1alpha1Backoff.maxDuration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cap, duration, factor, maxDuration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1Backoff {\n");
    sb.append("    cap: ").append(toIndentedString(cap)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    factor: ").append(toIndentedString(factor)).append("\n");
    sb.append("    maxDuration: ").append(toIndentedString(maxDuration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cap");
    openapiFields.add("duration");
    openapiFields.add("factor");
    openapiFields.add("maxDuration");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IoArgoprojWorkflowV1alpha1Backoff
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IoArgoprojWorkflowV1alpha1Backoff.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IoArgoprojWorkflowV1alpha1Backoff is not found in the empty JSON string", IoArgoprojWorkflowV1alpha1Backoff.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IoArgoprojWorkflowV1alpha1Backoff.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IoArgoprojWorkflowV1alpha1Backoff` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("cap") != null && !jsonObj.get("cap").isJsonNull()) && !jsonObj.get("cap").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cap` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cap").toString()));
      }
      if ((jsonObj.get("duration") != null && !jsonObj.get("duration").isJsonNull()) && !jsonObj.get("duration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `duration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("duration").toString()));
      }
      if ((jsonObj.get("factor") != null && !jsonObj.get("factor").isJsonNull()) && !jsonObj.get("factor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `factor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("factor").toString()));
      }
      if ((jsonObj.get("maxDuration") != null && !jsonObj.get("maxDuration").isJsonNull()) && !jsonObj.get("maxDuration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `maxDuration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("maxDuration").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IoArgoprojWorkflowV1alpha1Backoff.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IoArgoprojWorkflowV1alpha1Backoff' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IoArgoprojWorkflowV1alpha1Backoff> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IoArgoprojWorkflowV1alpha1Backoff.class));

       return (TypeAdapter<T>) new TypeAdapter<IoArgoprojWorkflowV1alpha1Backoff>() {
           @Override
           public void write(JsonWriter out, IoArgoprojWorkflowV1alpha1Backoff value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IoArgoprojWorkflowV1alpha1Backoff read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IoArgoprojWorkflowV1alpha1Backoff given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IoArgoprojWorkflowV1alpha1Backoff
   * @throws IOException if the JSON string is invalid with respect to IoArgoprojWorkflowV1alpha1Backoff
   */
  public static IoArgoprojWorkflowV1alpha1Backoff fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IoArgoprojWorkflowV1alpha1Backoff.class);
  }

  /**
   * Convert an instance of IoArgoprojWorkflowV1alpha1Backoff to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

