/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1EventSourceFilter;
import org.openapitools.client.model.IoK8sApiCoreV1SecretKeySelector;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PubSubEventSource refers to event-source for GCP PubSub related events.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-24T03:51:41.763920791Z[Etc/UTC]", comments = "Generator version: 7.12.0-SNAPSHOT")
public class IoArgoprojEventsV1alpha1PubSubEventSource {
  public static final String SERIALIZED_NAME_CREDENTIAL_SECRET = "credentialSecret";
  @SerializedName(SERIALIZED_NAME_CREDENTIAL_SECRET)
  @javax.annotation.Nullable
  private IoK8sApiCoreV1SecretKeySelector credentialSecret;

  public static final String SERIALIZED_NAME_DELETE_SUBSCRIPTION_ON_FINISH = "deleteSubscriptionOnFinish";
  @SerializedName(SERIALIZED_NAME_DELETE_SUBSCRIPTION_ON_FINISH)
  @javax.annotation.Nullable
  private Boolean deleteSubscriptionOnFinish;

  public static final String SERIALIZED_NAME_FILTER = "filter";
  @SerializedName(SERIALIZED_NAME_FILTER)
  @javax.annotation.Nullable
  private IoArgoprojEventsV1alpha1EventSourceFilter filter;

  public static final String SERIALIZED_NAME_JSON_BODY = "jsonBody";
  @SerializedName(SERIALIZED_NAME_JSON_BODY)
  @javax.annotation.Nullable
  private Boolean jsonBody;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private Map<String, String> metadata = new HashMap<>();

  public static final String SERIALIZED_NAME_PROJECT_I_D = "projectID";
  @SerializedName(SERIALIZED_NAME_PROJECT_I_D)
  @javax.annotation.Nullable
  private String projectID;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_I_D = "subscriptionID";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_I_D)
  @javax.annotation.Nullable
  private String subscriptionID;

  public static final String SERIALIZED_NAME_TOPIC = "topic";
  @SerializedName(SERIALIZED_NAME_TOPIC)
  @javax.annotation.Nullable
  private String topic;

  public static final String SERIALIZED_NAME_TOPIC_PROJECT_I_D = "topicProjectID";
  @SerializedName(SERIALIZED_NAME_TOPIC_PROJECT_I_D)
  @javax.annotation.Nullable
  private String topicProjectID;

  public IoArgoprojEventsV1alpha1PubSubEventSource() {
  }

  public IoArgoprojEventsV1alpha1PubSubEventSource credentialSecret(@javax.annotation.Nullable IoK8sApiCoreV1SecretKeySelector credentialSecret) {
    this.credentialSecret = credentialSecret;
    return this;
  }

  /**
   * Get credentialSecret
   * @return credentialSecret
   */
  @javax.annotation.Nullable
  public IoK8sApiCoreV1SecretKeySelector getCredentialSecret() {
    return credentialSecret;
  }

  public void setCredentialSecret(@javax.annotation.Nullable IoK8sApiCoreV1SecretKeySelector credentialSecret) {
    this.credentialSecret = credentialSecret;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource deleteSubscriptionOnFinish(@javax.annotation.Nullable Boolean deleteSubscriptionOnFinish) {
    this.deleteSubscriptionOnFinish = deleteSubscriptionOnFinish;
    return this;
  }

  /**
   * Get deleteSubscriptionOnFinish
   * @return deleteSubscriptionOnFinish
   */
  @javax.annotation.Nullable
  public Boolean getDeleteSubscriptionOnFinish() {
    return deleteSubscriptionOnFinish;
  }

  public void setDeleteSubscriptionOnFinish(@javax.annotation.Nullable Boolean deleteSubscriptionOnFinish) {
    this.deleteSubscriptionOnFinish = deleteSubscriptionOnFinish;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource filter(@javax.annotation.Nullable IoArgoprojEventsV1alpha1EventSourceFilter filter) {
    this.filter = filter;
    return this;
  }

  /**
   * Get filter
   * @return filter
   */
  @javax.annotation.Nullable
  public IoArgoprojEventsV1alpha1EventSourceFilter getFilter() {
    return filter;
  }

  public void setFilter(@javax.annotation.Nullable IoArgoprojEventsV1alpha1EventSourceFilter filter) {
    this.filter = filter;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource jsonBody(@javax.annotation.Nullable Boolean jsonBody) {
    this.jsonBody = jsonBody;
    return this;
  }

  /**
   * Get jsonBody
   * @return jsonBody
   */
  @javax.annotation.Nullable
  public Boolean getJsonBody() {
    return jsonBody;
  }

  public void setJsonBody(@javax.annotation.Nullable Boolean jsonBody) {
    this.jsonBody = jsonBody;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource metadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public IoArgoprojEventsV1alpha1PubSubEventSource putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource projectID(@javax.annotation.Nullable String projectID) {
    this.projectID = projectID;
    return this;
  }

  /**
   * Get projectID
   * @return projectID
   */
  @javax.annotation.Nullable
  public String getProjectID() {
    return projectID;
  }

  public void setProjectID(@javax.annotation.Nullable String projectID) {
    this.projectID = projectID;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource subscriptionID(@javax.annotation.Nullable String subscriptionID) {
    this.subscriptionID = subscriptionID;
    return this;
  }

  /**
   * Get subscriptionID
   * @return subscriptionID
   */
  @javax.annotation.Nullable
  public String getSubscriptionID() {
    return subscriptionID;
  }

  public void setSubscriptionID(@javax.annotation.Nullable String subscriptionID) {
    this.subscriptionID = subscriptionID;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource topic(@javax.annotation.Nullable String topic) {
    this.topic = topic;
    return this;
  }

  /**
   * Get topic
   * @return topic
   */
  @javax.annotation.Nullable
  public String getTopic() {
    return topic;
  }

  public void setTopic(@javax.annotation.Nullable String topic) {
    this.topic = topic;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource topicProjectID(@javax.annotation.Nullable String topicProjectID) {
    this.topicProjectID = topicProjectID;
    return this;
  }

  /**
   * Get topicProjectID
   * @return topicProjectID
   */
  @javax.annotation.Nullable
  public String getTopicProjectID() {
    return topicProjectID;
  }

  public void setTopicProjectID(@javax.annotation.Nullable String topicProjectID) {
    this.topicProjectID = topicProjectID;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojEventsV1alpha1PubSubEventSource ioArgoprojEventsV1alpha1PubSubEventSource = (IoArgoprojEventsV1alpha1PubSubEventSource) o;
    return Objects.equals(this.credentialSecret, ioArgoprojEventsV1alpha1PubSubEventSource.credentialSecret) &&
        Objects.equals(this.deleteSubscriptionOnFinish, ioArgoprojEventsV1alpha1PubSubEventSource.deleteSubscriptionOnFinish) &&
        Objects.equals(this.filter, ioArgoprojEventsV1alpha1PubSubEventSource.filter) &&
        Objects.equals(this.jsonBody, ioArgoprojEventsV1alpha1PubSubEventSource.jsonBody) &&
        Objects.equals(this.metadata, ioArgoprojEventsV1alpha1PubSubEventSource.metadata) &&
        Objects.equals(this.projectID, ioArgoprojEventsV1alpha1PubSubEventSource.projectID) &&
        Objects.equals(this.subscriptionID, ioArgoprojEventsV1alpha1PubSubEventSource.subscriptionID) &&
        Objects.equals(this.topic, ioArgoprojEventsV1alpha1PubSubEventSource.topic) &&
        Objects.equals(this.topicProjectID, ioArgoprojEventsV1alpha1PubSubEventSource.topicProjectID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(credentialSecret, deleteSubscriptionOnFinish, filter, jsonBody, metadata, projectID, subscriptionID, topic, topicProjectID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojEventsV1alpha1PubSubEventSource {\n");
    sb.append("    credentialSecret: ").append(toIndentedString(credentialSecret)).append("\n");
    sb.append("    deleteSubscriptionOnFinish: ").append(toIndentedString(deleteSubscriptionOnFinish)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    jsonBody: ").append(toIndentedString(jsonBody)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    projectID: ").append(toIndentedString(projectID)).append("\n");
    sb.append("    subscriptionID: ").append(toIndentedString(subscriptionID)).append("\n");
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("    topicProjectID: ").append(toIndentedString(topicProjectID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("credentialSecret");
    openapiFields.add("deleteSubscriptionOnFinish");
    openapiFields.add("filter");
    openapiFields.add("jsonBody");
    openapiFields.add("metadata");
    openapiFields.add("projectID");
    openapiFields.add("subscriptionID");
    openapiFields.add("topic");
    openapiFields.add("topicProjectID");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IoArgoprojEventsV1alpha1PubSubEventSource
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IoArgoprojEventsV1alpha1PubSubEventSource.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IoArgoprojEventsV1alpha1PubSubEventSource is not found in the empty JSON string", IoArgoprojEventsV1alpha1PubSubEventSource.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IoArgoprojEventsV1alpha1PubSubEventSource.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IoArgoprojEventsV1alpha1PubSubEventSource` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `credentialSecret`
      if (jsonObj.get("credentialSecret") != null && !jsonObj.get("credentialSecret").isJsonNull()) {
        IoK8sApiCoreV1SecretKeySelector.validateJsonElement(jsonObj.get("credentialSecret"));
      }
      // validate the optional field `filter`
      if (jsonObj.get("filter") != null && !jsonObj.get("filter").isJsonNull()) {
        IoArgoprojEventsV1alpha1EventSourceFilter.validateJsonElement(jsonObj.get("filter"));
      }
      if ((jsonObj.get("projectID") != null && !jsonObj.get("projectID").isJsonNull()) && !jsonObj.get("projectID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `projectID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("projectID").toString()));
      }
      if ((jsonObj.get("subscriptionID") != null && !jsonObj.get("subscriptionID").isJsonNull()) && !jsonObj.get("subscriptionID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subscriptionID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subscriptionID").toString()));
      }
      if ((jsonObj.get("topic") != null && !jsonObj.get("topic").isJsonNull()) && !jsonObj.get("topic").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `topic` to be a primitive type in the JSON string but got `%s`", jsonObj.get("topic").toString()));
      }
      if ((jsonObj.get("topicProjectID") != null && !jsonObj.get("topicProjectID").isJsonNull()) && !jsonObj.get("topicProjectID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `topicProjectID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("topicProjectID").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IoArgoprojEventsV1alpha1PubSubEventSource.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IoArgoprojEventsV1alpha1PubSubEventSource' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IoArgoprojEventsV1alpha1PubSubEventSource> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IoArgoprojEventsV1alpha1PubSubEventSource.class));

       return (TypeAdapter<T>) new TypeAdapter<IoArgoprojEventsV1alpha1PubSubEventSource>() {
           @Override
           public void write(JsonWriter out, IoArgoprojEventsV1alpha1PubSubEventSource value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IoArgoprojEventsV1alpha1PubSubEventSource read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IoArgoprojEventsV1alpha1PubSubEventSource given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IoArgoprojEventsV1alpha1PubSubEventSource
   * @throws IOException if the JSON string is invalid with respect to IoArgoprojEventsV1alpha1PubSubEventSource
   */
  public static IoArgoprojEventsV1alpha1PubSubEventSource fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IoArgoprojEventsV1alpha1PubSubEventSource.class);
  }

  /**
   * Convert an instance of IoArgoprojEventsV1alpha1PubSubEventSource to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

