/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Metadata;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * WorkflowLevelArtifactGC describes how to delete artifacts from completed Workflows - this spec is used on the Workflow level
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-24T03:51:41.763920791Z[Etc/UTC]", comments = "Generator version: 7.12.0-SNAPSHOT")
public class IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC {
  public static final String SERIALIZED_NAME_FORCE_FINALIZER_REMOVAL = "forceFinalizerRemoval";
  @SerializedName(SERIALIZED_NAME_FORCE_FINALIZER_REMOVAL)
  @javax.annotation.Nullable
  private Boolean forceFinalizerRemoval;

  public static final String SERIALIZED_NAME_POD_METADATA = "podMetadata";
  @SerializedName(SERIALIZED_NAME_POD_METADATA)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1Metadata podMetadata;

  public static final String SERIALIZED_NAME_POD_SPEC_PATCH = "podSpecPatch";
  @SerializedName(SERIALIZED_NAME_POD_SPEC_PATCH)
  @javax.annotation.Nullable
  private String podSpecPatch;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_NAME = "serviceAccountName";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_NAME)
  @javax.annotation.Nullable
  private String serviceAccountName;

  public static final String SERIALIZED_NAME_STRATEGY = "strategy";
  @SerializedName(SERIALIZED_NAME_STRATEGY)
  @javax.annotation.Nullable
  private String strategy;

  public IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC() {
  }

  public IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC forceFinalizerRemoval(@javax.annotation.Nullable Boolean forceFinalizerRemoval) {
    this.forceFinalizerRemoval = forceFinalizerRemoval;
    return this;
  }

  /**
   * ForceFinalizerRemoval: if set to true, the finalizer will be removed in the case that Artifact GC fails
   * @return forceFinalizerRemoval
   */
  @javax.annotation.Nullable
  public Boolean getForceFinalizerRemoval() {
    return forceFinalizerRemoval;
  }

  public void setForceFinalizerRemoval(@javax.annotation.Nullable Boolean forceFinalizerRemoval) {
    this.forceFinalizerRemoval = forceFinalizerRemoval;
  }


  public IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC podMetadata(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Metadata podMetadata) {
    this.podMetadata = podMetadata;
    return this;
  }

  /**
   * Get podMetadata
   * @return podMetadata
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1Metadata getPodMetadata() {
    return podMetadata;
  }

  public void setPodMetadata(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Metadata podMetadata) {
    this.podMetadata = podMetadata;
  }


  public IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC podSpecPatch(@javax.annotation.Nullable String podSpecPatch) {
    this.podSpecPatch = podSpecPatch;
    return this;
  }

  /**
   * PodSpecPatch holds strategic merge patch to apply against the artgc pod spec.
   * @return podSpecPatch
   */
  @javax.annotation.Nullable
  public String getPodSpecPatch() {
    return podSpecPatch;
  }

  public void setPodSpecPatch(@javax.annotation.Nullable String podSpecPatch) {
    this.podSpecPatch = podSpecPatch;
  }


  public IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC serviceAccountName(@javax.annotation.Nullable String serviceAccountName) {
    this.serviceAccountName = serviceAccountName;
    return this;
  }

  /**
   * ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion
   * @return serviceAccountName
   */
  @javax.annotation.Nullable
  public String getServiceAccountName() {
    return serviceAccountName;
  }

  public void setServiceAccountName(@javax.annotation.Nullable String serviceAccountName) {
    this.serviceAccountName = serviceAccountName;
  }


  public IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC strategy(@javax.annotation.Nullable String strategy) {
    this.strategy = strategy;
    return this;
  }

  /**
   * Strategy is the strategy to use.
   * @return strategy
   */
  @javax.annotation.Nullable
  public String getStrategy() {
    return strategy;
  }

  public void setStrategy(@javax.annotation.Nullable String strategy) {
    this.strategy = strategy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC ioArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC = (IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC) o;
    return Objects.equals(this.forceFinalizerRemoval, ioArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC.forceFinalizerRemoval) &&
        Objects.equals(this.podMetadata, ioArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC.podMetadata) &&
        Objects.equals(this.podSpecPatch, ioArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC.podSpecPatch) &&
        Objects.equals(this.serviceAccountName, ioArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC.serviceAccountName) &&
        Objects.equals(this.strategy, ioArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC.strategy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(forceFinalizerRemoval, podMetadata, podSpecPatch, serviceAccountName, strategy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC {\n");
    sb.append("    forceFinalizerRemoval: ").append(toIndentedString(forceFinalizerRemoval)).append("\n");
    sb.append("    podMetadata: ").append(toIndentedString(podMetadata)).append("\n");
    sb.append("    podSpecPatch: ").append(toIndentedString(podSpecPatch)).append("\n");
    sb.append("    serviceAccountName: ").append(toIndentedString(serviceAccountName)).append("\n");
    sb.append("    strategy: ").append(toIndentedString(strategy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("forceFinalizerRemoval");
    openapiFields.add("podMetadata");
    openapiFields.add("podSpecPatch");
    openapiFields.add("serviceAccountName");
    openapiFields.add("strategy");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC is not found in the empty JSON string", IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `podMetadata`
      if (jsonObj.get("podMetadata") != null && !jsonObj.get("podMetadata").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1Metadata.validateJsonElement(jsonObj.get("podMetadata"));
      }
      if ((jsonObj.get("podSpecPatch") != null && !jsonObj.get("podSpecPatch").isJsonNull()) && !jsonObj.get("podSpecPatch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `podSpecPatch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("podSpecPatch").toString()));
      }
      if ((jsonObj.get("serviceAccountName") != null && !jsonObj.get("serviceAccountName").isJsonNull()) && !jsonObj.get("serviceAccountName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serviceAccountName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serviceAccountName").toString()));
      }
      if ((jsonObj.get("strategy") != null && !jsonObj.get("strategy").isJsonNull()) && !jsonObj.get("strategy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `strategy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("strategy").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC.class));

       return (TypeAdapter<T>) new TypeAdapter<IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC>() {
           @Override
           public void write(JsonWriter out, IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC
   * @throws IOException if the JSON string is invalid with respect to IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC
   */
  public static IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC.class);
  }

  /**
   * Convert an instance of IoArgoprojWorkflowV1alpha1WorkflowLevelArtifactGC to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

