/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1ArtifactLocation;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1ContainerSetTemplate;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1DAGTemplate;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Data;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1ExecutorConfig;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1HTTP;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Inputs;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Memoize;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Metadata;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Metrics;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Outputs;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1ResourceTemplate;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1RetryStrategy;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1ScriptTemplate;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1SuspendTemplate;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1Synchronization;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1UserContainer;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1WorkflowStep;
import org.openapitools.client.model.IoK8sApiCoreV1Affinity;
import org.openapitools.client.model.IoK8sApiCoreV1Container;
import org.openapitools.client.model.IoK8sApiCoreV1HostAlias;
import org.openapitools.client.model.IoK8sApiCoreV1PodSecurityContext;
import org.openapitools.client.model.IoK8sApiCoreV1Toleration;
import org.openapitools.client.model.IoK8sApiCoreV1Volume;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Template is a reusable and composable unit of execution in a workflow
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-24T03:51:41.763920791Z[Etc/UTC]", comments = "Generator version: 7.12.0-SNAPSHOT")
public class IoArgoprojWorkflowV1alpha1Template {
  public static final String SERIALIZED_NAME_ACTIVE_DEADLINE_SECONDS = "activeDeadlineSeconds";
  @SerializedName(SERIALIZED_NAME_ACTIVE_DEADLINE_SECONDS)
  @javax.annotation.Nullable
  private String activeDeadlineSeconds;

  public static final String SERIALIZED_NAME_AFFINITY = "affinity";
  @SerializedName(SERIALIZED_NAME_AFFINITY)
  @javax.annotation.Nullable
  private IoK8sApiCoreV1Affinity affinity;

  public static final String SERIALIZED_NAME_ANNOTATIONS = "annotations";
  @SerializedName(SERIALIZED_NAME_ANNOTATIONS)
  @javax.annotation.Nullable
  private Map<String, String> annotations = new HashMap<>();

  public static final String SERIALIZED_NAME_ARCHIVE_LOCATION = "archiveLocation";
  @SerializedName(SERIALIZED_NAME_ARCHIVE_LOCATION)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1ArtifactLocation archiveLocation;

  public static final String SERIALIZED_NAME_AUTOMOUNT_SERVICE_ACCOUNT_TOKEN = "automountServiceAccountToken";
  @SerializedName(SERIALIZED_NAME_AUTOMOUNT_SERVICE_ACCOUNT_TOKEN)
  @javax.annotation.Nullable
  private Boolean automountServiceAccountToken;

  public static final String SERIALIZED_NAME_CONTAINER = "container";
  @SerializedName(SERIALIZED_NAME_CONTAINER)
  @javax.annotation.Nullable
  private IoK8sApiCoreV1Container container;

  public static final String SERIALIZED_NAME_CONTAINER_SET = "containerSet";
  @SerializedName(SERIALIZED_NAME_CONTAINER_SET)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1ContainerSetTemplate containerSet;

  public static final String SERIALIZED_NAME_DAEMON = "daemon";
  @SerializedName(SERIALIZED_NAME_DAEMON)
  @javax.annotation.Nullable
  private Boolean daemon;

  public static final String SERIALIZED_NAME_DAG = "dag";
  @SerializedName(SERIALIZED_NAME_DAG)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1DAGTemplate dag;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1Data data;

  public static final String SERIALIZED_NAME_EXECUTOR = "executor";
  @SerializedName(SERIALIZED_NAME_EXECUTOR)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1ExecutorConfig executor;

  public static final String SERIALIZED_NAME_FAIL_FAST = "failFast";
  @SerializedName(SERIALIZED_NAME_FAIL_FAST)
  @javax.annotation.Nullable
  private Boolean failFast;

  public static final String SERIALIZED_NAME_HOST_ALIASES = "hostAliases";
  @SerializedName(SERIALIZED_NAME_HOST_ALIASES)
  @javax.annotation.Nullable
  private List<IoK8sApiCoreV1HostAlias> hostAliases = new ArrayList<>();

  public static final String SERIALIZED_NAME_HTTP = "http";
  @SerializedName(SERIALIZED_NAME_HTTP)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1HTTP http;

  public static final String SERIALIZED_NAME_INIT_CONTAINERS = "initContainers";
  @SerializedName(SERIALIZED_NAME_INIT_CONTAINERS)
  @javax.annotation.Nullable
  private List<IoArgoprojWorkflowV1alpha1UserContainer> initContainers = new ArrayList<>();

  public static final String SERIALIZED_NAME_INPUTS = "inputs";
  @SerializedName(SERIALIZED_NAME_INPUTS)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1Inputs inputs;

  public static final String SERIALIZED_NAME_MEMOIZE = "memoize";
  @SerializedName(SERIALIZED_NAME_MEMOIZE)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1Memoize memoize;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1Metadata metadata;

  public static final String SERIALIZED_NAME_METRICS = "metrics";
  @SerializedName(SERIALIZED_NAME_METRICS)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1Metrics metrics;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_NODE_SELECTOR = "nodeSelector";
  @SerializedName(SERIALIZED_NAME_NODE_SELECTOR)
  @javax.annotation.Nullable
  private Map<String, String> nodeSelector = new HashMap<>();

  public static final String SERIALIZED_NAME_OUTPUTS = "outputs";
  @SerializedName(SERIALIZED_NAME_OUTPUTS)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1Outputs outputs;

  public static final String SERIALIZED_NAME_PARALLELISM = "parallelism";
  @SerializedName(SERIALIZED_NAME_PARALLELISM)
  @javax.annotation.Nullable
  private Integer parallelism;

  public static final String SERIALIZED_NAME_PLUGIN = "plugin";
  @SerializedName(SERIALIZED_NAME_PLUGIN)
  @javax.annotation.Nullable
  private Object plugin;

  public static final String SERIALIZED_NAME_POD_SPEC_PATCH = "podSpecPatch";
  @SerializedName(SERIALIZED_NAME_POD_SPEC_PATCH)
  @javax.annotation.Nullable
  private String podSpecPatch;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  @javax.annotation.Nullable
  private Integer priority;

  public static final String SERIALIZED_NAME_PRIORITY_CLASS_NAME = "priorityClassName";
  @SerializedName(SERIALIZED_NAME_PRIORITY_CLASS_NAME)
  @javax.annotation.Nullable
  private String priorityClassName;

  public static final String SERIALIZED_NAME_RESOURCE = "resource";
  @SerializedName(SERIALIZED_NAME_RESOURCE)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1ResourceTemplate resource;

  public static final String SERIALIZED_NAME_RETRY_STRATEGY = "retryStrategy";
  @SerializedName(SERIALIZED_NAME_RETRY_STRATEGY)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1RetryStrategy retryStrategy;

  public static final String SERIALIZED_NAME_SCHEDULER_NAME = "schedulerName";
  @SerializedName(SERIALIZED_NAME_SCHEDULER_NAME)
  @javax.annotation.Nullable
  private String schedulerName;

  public static final String SERIALIZED_NAME_SCRIPT = "script";
  @SerializedName(SERIALIZED_NAME_SCRIPT)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1ScriptTemplate script;

  public static final String SERIALIZED_NAME_SECURITY_CONTEXT = "securityContext";
  @SerializedName(SERIALIZED_NAME_SECURITY_CONTEXT)
  @javax.annotation.Nullable
  private IoK8sApiCoreV1PodSecurityContext securityContext;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_NAME = "serviceAccountName";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_NAME)
  @javax.annotation.Nullable
  private String serviceAccountName;

  public static final String SERIALIZED_NAME_SIDECARS = "sidecars";
  @SerializedName(SERIALIZED_NAME_SIDECARS)
  @javax.annotation.Nullable
  private List<IoArgoprojWorkflowV1alpha1UserContainer> sidecars = new ArrayList<>();

  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  @javax.annotation.Nullable
  private List<List<IoArgoprojWorkflowV1alpha1WorkflowStep>> steps = new ArrayList<>();

  public static final String SERIALIZED_NAME_SUSPEND = "suspend";
  @SerializedName(SERIALIZED_NAME_SUSPEND)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1SuspendTemplate suspend;

  public static final String SERIALIZED_NAME_SYNCHRONIZATION = "synchronization";
  @SerializedName(SERIALIZED_NAME_SYNCHRONIZATION)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1Synchronization synchronization;

  public static final String SERIALIZED_NAME_TIMEOUT = "timeout";
  @SerializedName(SERIALIZED_NAME_TIMEOUT)
  @javax.annotation.Nullable
  private String timeout;

  public static final String SERIALIZED_NAME_TOLERATIONS = "tolerations";
  @SerializedName(SERIALIZED_NAME_TOLERATIONS)
  @javax.annotation.Nullable
  private List<IoK8sApiCoreV1Toleration> tolerations = new ArrayList<>();

  public static final String SERIALIZED_NAME_VOLUMES = "volumes";
  @SerializedName(SERIALIZED_NAME_VOLUMES)
  @javax.annotation.Nullable
  private List<IoK8sApiCoreV1Volume> volumes = new ArrayList<>();

  public IoArgoprojWorkflowV1alpha1Template() {
  }

  public IoArgoprojWorkflowV1alpha1Template activeDeadlineSeconds(@javax.annotation.Nullable String activeDeadlineSeconds) {
    this.activeDeadlineSeconds = activeDeadlineSeconds;
    return this;
  }

  /**
   * Get activeDeadlineSeconds
   * @return activeDeadlineSeconds
   */
  @javax.annotation.Nullable
  public String getActiveDeadlineSeconds() {
    return activeDeadlineSeconds;
  }

  public void setActiveDeadlineSeconds(@javax.annotation.Nullable String activeDeadlineSeconds) {
    this.activeDeadlineSeconds = activeDeadlineSeconds;
  }


  public IoArgoprojWorkflowV1alpha1Template affinity(@javax.annotation.Nullable IoK8sApiCoreV1Affinity affinity) {
    this.affinity = affinity;
    return this;
  }

  /**
   * Get affinity
   * @return affinity
   */
  @javax.annotation.Nullable
  public IoK8sApiCoreV1Affinity getAffinity() {
    return affinity;
  }

  public void setAffinity(@javax.annotation.Nullable IoK8sApiCoreV1Affinity affinity) {
    this.affinity = affinity;
  }


  public IoArgoprojWorkflowV1alpha1Template annotations(@javax.annotation.Nullable Map<String, String> annotations) {
    this.annotations = annotations;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1Template putAnnotationsItem(String key, String annotationsItem) {
    if (this.annotations == null) {
      this.annotations = new HashMap<>();
    }
    this.annotations.put(key, annotationsItem);
    return this;
  }

  /**
   * Annotations is a list of annotations to add to the template at runtime
   * @return annotations
   */
  @javax.annotation.Nullable
  public Map<String, String> getAnnotations() {
    return annotations;
  }

  public void setAnnotations(@javax.annotation.Nullable Map<String, String> annotations) {
    this.annotations = annotations;
  }


  public IoArgoprojWorkflowV1alpha1Template archiveLocation(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1ArtifactLocation archiveLocation) {
    this.archiveLocation = archiveLocation;
    return this;
  }

  /**
   * Get archiveLocation
   * @return archiveLocation
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1ArtifactLocation getArchiveLocation() {
    return archiveLocation;
  }

  public void setArchiveLocation(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1ArtifactLocation archiveLocation) {
    this.archiveLocation = archiveLocation;
  }


  public IoArgoprojWorkflowV1alpha1Template automountServiceAccountToken(@javax.annotation.Nullable Boolean automountServiceAccountToken) {
    this.automountServiceAccountToken = automountServiceAccountToken;
    return this;
  }

  /**
   * AutomountServiceAccountToken indicates whether a service account token should be automatically mounted in pods. ServiceAccountName of ExecutorConfig must be specified if this value is false.
   * @return automountServiceAccountToken
   */
  @javax.annotation.Nullable
  public Boolean getAutomountServiceAccountToken() {
    return automountServiceAccountToken;
  }

  public void setAutomountServiceAccountToken(@javax.annotation.Nullable Boolean automountServiceAccountToken) {
    this.automountServiceAccountToken = automountServiceAccountToken;
  }


  public IoArgoprojWorkflowV1alpha1Template container(@javax.annotation.Nullable IoK8sApiCoreV1Container container) {
    this.container = container;
    return this;
  }

  /**
   * Get container
   * @return container
   */
  @javax.annotation.Nullable
  public IoK8sApiCoreV1Container getContainer() {
    return container;
  }

  public void setContainer(@javax.annotation.Nullable IoK8sApiCoreV1Container container) {
    this.container = container;
  }


  public IoArgoprojWorkflowV1alpha1Template containerSet(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1ContainerSetTemplate containerSet) {
    this.containerSet = containerSet;
    return this;
  }

  /**
   * Get containerSet
   * @return containerSet
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1ContainerSetTemplate getContainerSet() {
    return containerSet;
  }

  public void setContainerSet(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1ContainerSetTemplate containerSet) {
    this.containerSet = containerSet;
  }


  public IoArgoprojWorkflowV1alpha1Template daemon(@javax.annotation.Nullable Boolean daemon) {
    this.daemon = daemon;
    return this;
  }

  /**
   * Daemon will allow a workflow to proceed to the next step so long as the container reaches readiness
   * @return daemon
   */
  @javax.annotation.Nullable
  public Boolean getDaemon() {
    return daemon;
  }

  public void setDaemon(@javax.annotation.Nullable Boolean daemon) {
    this.daemon = daemon;
  }


  public IoArgoprojWorkflowV1alpha1Template dag(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1DAGTemplate dag) {
    this.dag = dag;
    return this;
  }

  /**
   * Get dag
   * @return dag
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1DAGTemplate getDag() {
    return dag;
  }

  public void setDag(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1DAGTemplate dag) {
    this.dag = dag;
  }


  public IoArgoprojWorkflowV1alpha1Template data(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Data data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1Data getData() {
    return data;
  }

  public void setData(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Data data) {
    this.data = data;
  }


  public IoArgoprojWorkflowV1alpha1Template executor(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1ExecutorConfig executor) {
    this.executor = executor;
    return this;
  }

  /**
   * Get executor
   * @return executor
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1ExecutorConfig getExecutor() {
    return executor;
  }

  public void setExecutor(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1ExecutorConfig executor) {
    this.executor = executor;
  }


  public IoArgoprojWorkflowV1alpha1Template failFast(@javax.annotation.Nullable Boolean failFast) {
    this.failFast = failFast;
    return this;
  }

  /**
   * FailFast, if specified, will fail this template if any of its child pods has failed. This is useful for when this template is expanded with &#x60;withItems&#x60;, etc.
   * @return failFast
   */
  @javax.annotation.Nullable
  public Boolean getFailFast() {
    return failFast;
  }

  public void setFailFast(@javax.annotation.Nullable Boolean failFast) {
    this.failFast = failFast;
  }


  public IoArgoprojWorkflowV1alpha1Template hostAliases(@javax.annotation.Nullable List<IoK8sApiCoreV1HostAlias> hostAliases) {
    this.hostAliases = hostAliases;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1Template addHostAliasesItem(IoK8sApiCoreV1HostAlias hostAliasesItem) {
    if (this.hostAliases == null) {
      this.hostAliases = new ArrayList<>();
    }
    this.hostAliases.add(hostAliasesItem);
    return this;
  }

  /**
   * HostAliases is an optional list of hosts and IPs that will be injected into the pod spec
   * @return hostAliases
   */
  @javax.annotation.Nullable
  public List<IoK8sApiCoreV1HostAlias> getHostAliases() {
    return hostAliases;
  }

  public void setHostAliases(@javax.annotation.Nullable List<IoK8sApiCoreV1HostAlias> hostAliases) {
    this.hostAliases = hostAliases;
  }


  public IoArgoprojWorkflowV1alpha1Template http(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1HTTP http) {
    this.http = http;
    return this;
  }

  /**
   * Get http
   * @return http
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1HTTP getHttp() {
    return http;
  }

  public void setHttp(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1HTTP http) {
    this.http = http;
  }


  public IoArgoprojWorkflowV1alpha1Template initContainers(@javax.annotation.Nullable List<IoArgoprojWorkflowV1alpha1UserContainer> initContainers) {
    this.initContainers = initContainers;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1Template addInitContainersItem(IoArgoprojWorkflowV1alpha1UserContainer initContainersItem) {
    if (this.initContainers == null) {
      this.initContainers = new ArrayList<>();
    }
    this.initContainers.add(initContainersItem);
    return this;
  }

  /**
   * InitContainers is a list of containers which run before the main container.
   * @return initContainers
   */
  @javax.annotation.Nullable
  public List<IoArgoprojWorkflowV1alpha1UserContainer> getInitContainers() {
    return initContainers;
  }

  public void setInitContainers(@javax.annotation.Nullable List<IoArgoprojWorkflowV1alpha1UserContainer> initContainers) {
    this.initContainers = initContainers;
  }


  public IoArgoprojWorkflowV1alpha1Template inputs(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Inputs inputs) {
    this.inputs = inputs;
    return this;
  }

  /**
   * Get inputs
   * @return inputs
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1Inputs getInputs() {
    return inputs;
  }

  public void setInputs(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Inputs inputs) {
    this.inputs = inputs;
  }


  public IoArgoprojWorkflowV1alpha1Template memoize(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Memoize memoize) {
    this.memoize = memoize;
    return this;
  }

  /**
   * Get memoize
   * @return memoize
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1Memoize getMemoize() {
    return memoize;
  }

  public void setMemoize(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Memoize memoize) {
    this.memoize = memoize;
  }


  public IoArgoprojWorkflowV1alpha1Template metadata(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Metadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1Metadata getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Metadata metadata) {
    this.metadata = metadata;
  }


  public IoArgoprojWorkflowV1alpha1Template metrics(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Metrics metrics) {
    this.metrics = metrics;
    return this;
  }

  /**
   * Get metrics
   * @return metrics
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1Metrics getMetrics() {
    return metrics;
  }

  public void setMetrics(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Metrics metrics) {
    this.metrics = metrics;
  }


  public IoArgoprojWorkflowV1alpha1Template name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Name is the name of the template
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public IoArgoprojWorkflowV1alpha1Template nodeSelector(@javax.annotation.Nullable Map<String, String> nodeSelector) {
    this.nodeSelector = nodeSelector;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1Template putNodeSelectorItem(String key, String nodeSelectorItem) {
    if (this.nodeSelector == null) {
      this.nodeSelector = new HashMap<>();
    }
    this.nodeSelector.put(key, nodeSelectorItem);
    return this;
  }

  /**
   * NodeSelector is a selector to schedule this step of the workflow to be run on the selected node(s). Overrides the selector set at the workflow level.
   * @return nodeSelector
   */
  @javax.annotation.Nullable
  public Map<String, String> getNodeSelector() {
    return nodeSelector;
  }

  public void setNodeSelector(@javax.annotation.Nullable Map<String, String> nodeSelector) {
    this.nodeSelector = nodeSelector;
  }


  public IoArgoprojWorkflowV1alpha1Template outputs(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Outputs outputs) {
    this.outputs = outputs;
    return this;
  }

  /**
   * Get outputs
   * @return outputs
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1Outputs getOutputs() {
    return outputs;
  }

  public void setOutputs(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Outputs outputs) {
    this.outputs = outputs;
  }


  public IoArgoprojWorkflowV1alpha1Template parallelism(@javax.annotation.Nullable Integer parallelism) {
    this.parallelism = parallelism;
    return this;
  }

  /**
   * Parallelism limits the max total parallel pods that can execute at the same time within the boundaries of this template invocation. If additional steps/dag templates are invoked, the pods created by those templates will not be counted towards this total.
   * @return parallelism
   */
  @javax.annotation.Nullable
  public Integer getParallelism() {
    return parallelism;
  }

  public void setParallelism(@javax.annotation.Nullable Integer parallelism) {
    this.parallelism = parallelism;
  }


  public IoArgoprojWorkflowV1alpha1Template plugin(@javax.annotation.Nullable Object plugin) {
    this.plugin = plugin;
    return this;
  }

  /**
   * Plugin is an Object with exactly one key
   * @return plugin
   */
  @javax.annotation.Nullable
  public Object getPlugin() {
    return plugin;
  }

  public void setPlugin(@javax.annotation.Nullable Object plugin) {
    this.plugin = plugin;
  }


  public IoArgoprojWorkflowV1alpha1Template podSpecPatch(@javax.annotation.Nullable String podSpecPatch) {
    this.podSpecPatch = podSpecPatch;
    return this;
  }

  /**
   * PodSpecPatch holds strategic merge patch to apply against the pod spec. Allows parameterization of container fields which are not strings (e.g. resource limits).
   * @return podSpecPatch
   */
  @javax.annotation.Nullable
  public String getPodSpecPatch() {
    return podSpecPatch;
  }

  public void setPodSpecPatch(@javax.annotation.Nullable String podSpecPatch) {
    this.podSpecPatch = podSpecPatch;
  }


  public IoArgoprojWorkflowV1alpha1Template priority(@javax.annotation.Nullable Integer priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Priority to apply to workflow pods.
   * @return priority
   */
  @javax.annotation.Nullable
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(@javax.annotation.Nullable Integer priority) {
    this.priority = priority;
  }


  public IoArgoprojWorkflowV1alpha1Template priorityClassName(@javax.annotation.Nullable String priorityClassName) {
    this.priorityClassName = priorityClassName;
    return this;
  }

  /**
   * PriorityClassName to apply to workflow pods.
   * @return priorityClassName
   */
  @javax.annotation.Nullable
  public String getPriorityClassName() {
    return priorityClassName;
  }

  public void setPriorityClassName(@javax.annotation.Nullable String priorityClassName) {
    this.priorityClassName = priorityClassName;
  }


  public IoArgoprojWorkflowV1alpha1Template resource(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1ResourceTemplate resource) {
    this.resource = resource;
    return this;
  }

  /**
   * Get resource
   * @return resource
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1ResourceTemplate getResource() {
    return resource;
  }

  public void setResource(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1ResourceTemplate resource) {
    this.resource = resource;
  }


  public IoArgoprojWorkflowV1alpha1Template retryStrategy(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1RetryStrategy retryStrategy) {
    this.retryStrategy = retryStrategy;
    return this;
  }

  /**
   * Get retryStrategy
   * @return retryStrategy
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1RetryStrategy getRetryStrategy() {
    return retryStrategy;
  }

  public void setRetryStrategy(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1RetryStrategy retryStrategy) {
    this.retryStrategy = retryStrategy;
  }


  public IoArgoprojWorkflowV1alpha1Template schedulerName(@javax.annotation.Nullable String schedulerName) {
    this.schedulerName = schedulerName;
    return this;
  }

  /**
   * If specified, the pod will be dispatched by specified scheduler. Or it will be dispatched by workflow scope scheduler if specified. If neither specified, the pod will be dispatched by default scheduler.
   * @return schedulerName
   */
  @javax.annotation.Nullable
  public String getSchedulerName() {
    return schedulerName;
  }

  public void setSchedulerName(@javax.annotation.Nullable String schedulerName) {
    this.schedulerName = schedulerName;
  }


  public IoArgoprojWorkflowV1alpha1Template script(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1ScriptTemplate script) {
    this.script = script;
    return this;
  }

  /**
   * Get script
   * @return script
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1ScriptTemplate getScript() {
    return script;
  }

  public void setScript(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1ScriptTemplate script) {
    this.script = script;
  }


  public IoArgoprojWorkflowV1alpha1Template securityContext(@javax.annotation.Nullable IoK8sApiCoreV1PodSecurityContext securityContext) {
    this.securityContext = securityContext;
    return this;
  }

  /**
   * Get securityContext
   * @return securityContext
   */
  @javax.annotation.Nullable
  public IoK8sApiCoreV1PodSecurityContext getSecurityContext() {
    return securityContext;
  }

  public void setSecurityContext(@javax.annotation.Nullable IoK8sApiCoreV1PodSecurityContext securityContext) {
    this.securityContext = securityContext;
  }


  public IoArgoprojWorkflowV1alpha1Template serviceAccountName(@javax.annotation.Nullable String serviceAccountName) {
    this.serviceAccountName = serviceAccountName;
    return this;
  }

  /**
   * ServiceAccountName to apply to workflow pods
   * @return serviceAccountName
   */
  @javax.annotation.Nullable
  public String getServiceAccountName() {
    return serviceAccountName;
  }

  public void setServiceAccountName(@javax.annotation.Nullable String serviceAccountName) {
    this.serviceAccountName = serviceAccountName;
  }


  public IoArgoprojWorkflowV1alpha1Template sidecars(@javax.annotation.Nullable List<IoArgoprojWorkflowV1alpha1UserContainer> sidecars) {
    this.sidecars = sidecars;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1Template addSidecarsItem(IoArgoprojWorkflowV1alpha1UserContainer sidecarsItem) {
    if (this.sidecars == null) {
      this.sidecars = new ArrayList<>();
    }
    this.sidecars.add(sidecarsItem);
    return this;
  }

  /**
   * Sidecars is a list of containers which run alongside the main container Sidecars are automatically killed when the main container completes
   * @return sidecars
   */
  @javax.annotation.Nullable
  public List<IoArgoprojWorkflowV1alpha1UserContainer> getSidecars() {
    return sidecars;
  }

  public void setSidecars(@javax.annotation.Nullable List<IoArgoprojWorkflowV1alpha1UserContainer> sidecars) {
    this.sidecars = sidecars;
  }


  public IoArgoprojWorkflowV1alpha1Template steps(@javax.annotation.Nullable List<List<IoArgoprojWorkflowV1alpha1WorkflowStep>> steps) {
    this.steps = steps;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1Template addStepsItem(List<IoArgoprojWorkflowV1alpha1WorkflowStep> stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<>();
    }
    this.steps.add(stepsItem);
    return this;
  }

  /**
   * Steps define a series of sequential/parallel workflow steps
   * @return steps
   */
  @javax.annotation.Nullable
  public List<List<IoArgoprojWorkflowV1alpha1WorkflowStep>> getSteps() {
    return steps;
  }

  public void setSteps(@javax.annotation.Nullable List<List<IoArgoprojWorkflowV1alpha1WorkflowStep>> steps) {
    this.steps = steps;
  }


  public IoArgoprojWorkflowV1alpha1Template suspend(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1SuspendTemplate suspend) {
    this.suspend = suspend;
    return this;
  }

  /**
   * Get suspend
   * @return suspend
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1SuspendTemplate getSuspend() {
    return suspend;
  }

  public void setSuspend(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1SuspendTemplate suspend) {
    this.suspend = suspend;
  }


  public IoArgoprojWorkflowV1alpha1Template synchronization(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Synchronization synchronization) {
    this.synchronization = synchronization;
    return this;
  }

  /**
   * Get synchronization
   * @return synchronization
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1Synchronization getSynchronization() {
    return synchronization;
  }

  public void setSynchronization(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1Synchronization synchronization) {
    this.synchronization = synchronization;
  }


  public IoArgoprojWorkflowV1alpha1Template timeout(@javax.annotation.Nullable String timeout) {
    this.timeout = timeout;
    return this;
  }

  /**
   * Timeout allows to set the total node execution timeout duration counting from the node&#39;s start time. This duration also includes time in which the node spends in Pending state. This duration may not be applied to Step or DAG templates.
   * @return timeout
   */
  @javax.annotation.Nullable
  public String getTimeout() {
    return timeout;
  }

  public void setTimeout(@javax.annotation.Nullable String timeout) {
    this.timeout = timeout;
  }


  public IoArgoprojWorkflowV1alpha1Template tolerations(@javax.annotation.Nullable List<IoK8sApiCoreV1Toleration> tolerations) {
    this.tolerations = tolerations;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1Template addTolerationsItem(IoK8sApiCoreV1Toleration tolerationsItem) {
    if (this.tolerations == null) {
      this.tolerations = new ArrayList<>();
    }
    this.tolerations.add(tolerationsItem);
    return this;
  }

  /**
   * Tolerations to apply to workflow pods.
   * @return tolerations
   */
  @javax.annotation.Nullable
  public List<IoK8sApiCoreV1Toleration> getTolerations() {
    return tolerations;
  }

  public void setTolerations(@javax.annotation.Nullable List<IoK8sApiCoreV1Toleration> tolerations) {
    this.tolerations = tolerations;
  }


  public IoArgoprojWorkflowV1alpha1Template volumes(@javax.annotation.Nullable List<IoK8sApiCoreV1Volume> volumes) {
    this.volumes = volumes;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1Template addVolumesItem(IoK8sApiCoreV1Volume volumesItem) {
    if (this.volumes == null) {
      this.volumes = new ArrayList<>();
    }
    this.volumes.add(volumesItem);
    return this;
  }

  /**
   * Volumes is a list of volumes that can be mounted by containers in a template.
   * @return volumes
   */
  @javax.annotation.Nullable
  public List<IoK8sApiCoreV1Volume> getVolumes() {
    return volumes;
  }

  public void setVolumes(@javax.annotation.Nullable List<IoK8sApiCoreV1Volume> volumes) {
    this.volumes = volumes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1Template ioArgoprojWorkflowV1alpha1Template = (IoArgoprojWorkflowV1alpha1Template) o;
    return Objects.equals(this.activeDeadlineSeconds, ioArgoprojWorkflowV1alpha1Template.activeDeadlineSeconds) &&
        Objects.equals(this.affinity, ioArgoprojWorkflowV1alpha1Template.affinity) &&
        Objects.equals(this.annotations, ioArgoprojWorkflowV1alpha1Template.annotations) &&
        Objects.equals(this.archiveLocation, ioArgoprojWorkflowV1alpha1Template.archiveLocation) &&
        Objects.equals(this.automountServiceAccountToken, ioArgoprojWorkflowV1alpha1Template.automountServiceAccountToken) &&
        Objects.equals(this.container, ioArgoprojWorkflowV1alpha1Template.container) &&
        Objects.equals(this.containerSet, ioArgoprojWorkflowV1alpha1Template.containerSet) &&
        Objects.equals(this.daemon, ioArgoprojWorkflowV1alpha1Template.daemon) &&
        Objects.equals(this.dag, ioArgoprojWorkflowV1alpha1Template.dag) &&
        Objects.equals(this.data, ioArgoprojWorkflowV1alpha1Template.data) &&
        Objects.equals(this.executor, ioArgoprojWorkflowV1alpha1Template.executor) &&
        Objects.equals(this.failFast, ioArgoprojWorkflowV1alpha1Template.failFast) &&
        Objects.equals(this.hostAliases, ioArgoprojWorkflowV1alpha1Template.hostAliases) &&
        Objects.equals(this.http, ioArgoprojWorkflowV1alpha1Template.http) &&
        Objects.equals(this.initContainers, ioArgoprojWorkflowV1alpha1Template.initContainers) &&
        Objects.equals(this.inputs, ioArgoprojWorkflowV1alpha1Template.inputs) &&
        Objects.equals(this.memoize, ioArgoprojWorkflowV1alpha1Template.memoize) &&
        Objects.equals(this.metadata, ioArgoprojWorkflowV1alpha1Template.metadata) &&
        Objects.equals(this.metrics, ioArgoprojWorkflowV1alpha1Template.metrics) &&
        Objects.equals(this.name, ioArgoprojWorkflowV1alpha1Template.name) &&
        Objects.equals(this.nodeSelector, ioArgoprojWorkflowV1alpha1Template.nodeSelector) &&
        Objects.equals(this.outputs, ioArgoprojWorkflowV1alpha1Template.outputs) &&
        Objects.equals(this.parallelism, ioArgoprojWorkflowV1alpha1Template.parallelism) &&
        Objects.equals(this.plugin, ioArgoprojWorkflowV1alpha1Template.plugin) &&
        Objects.equals(this.podSpecPatch, ioArgoprojWorkflowV1alpha1Template.podSpecPatch) &&
        Objects.equals(this.priority, ioArgoprojWorkflowV1alpha1Template.priority) &&
        Objects.equals(this.priorityClassName, ioArgoprojWorkflowV1alpha1Template.priorityClassName) &&
        Objects.equals(this.resource, ioArgoprojWorkflowV1alpha1Template.resource) &&
        Objects.equals(this.retryStrategy, ioArgoprojWorkflowV1alpha1Template.retryStrategy) &&
        Objects.equals(this.schedulerName, ioArgoprojWorkflowV1alpha1Template.schedulerName) &&
        Objects.equals(this.script, ioArgoprojWorkflowV1alpha1Template.script) &&
        Objects.equals(this.securityContext, ioArgoprojWorkflowV1alpha1Template.securityContext) &&
        Objects.equals(this.serviceAccountName, ioArgoprojWorkflowV1alpha1Template.serviceAccountName) &&
        Objects.equals(this.sidecars, ioArgoprojWorkflowV1alpha1Template.sidecars) &&
        Objects.equals(this.steps, ioArgoprojWorkflowV1alpha1Template.steps) &&
        Objects.equals(this.suspend, ioArgoprojWorkflowV1alpha1Template.suspend) &&
        Objects.equals(this.synchronization, ioArgoprojWorkflowV1alpha1Template.synchronization) &&
        Objects.equals(this.timeout, ioArgoprojWorkflowV1alpha1Template.timeout) &&
        Objects.equals(this.tolerations, ioArgoprojWorkflowV1alpha1Template.tolerations) &&
        Objects.equals(this.volumes, ioArgoprojWorkflowV1alpha1Template.volumes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeDeadlineSeconds, affinity, annotations, archiveLocation, automountServiceAccountToken, container, containerSet, daemon, dag, data, executor, failFast, hostAliases, http, initContainers, inputs, memoize, metadata, metrics, name, nodeSelector, outputs, parallelism, plugin, podSpecPatch, priority, priorityClassName, resource, retryStrategy, schedulerName, script, securityContext, serviceAccountName, sidecars, steps, suspend, synchronization, timeout, tolerations, volumes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1Template {\n");
    sb.append("    activeDeadlineSeconds: ").append(toIndentedString(activeDeadlineSeconds)).append("\n");
    sb.append("    affinity: ").append(toIndentedString(affinity)).append("\n");
    sb.append("    annotations: ").append(toIndentedString(annotations)).append("\n");
    sb.append("    archiveLocation: ").append(toIndentedString(archiveLocation)).append("\n");
    sb.append("    automountServiceAccountToken: ").append(toIndentedString(automountServiceAccountToken)).append("\n");
    sb.append("    container: ").append(toIndentedString(container)).append("\n");
    sb.append("    containerSet: ").append(toIndentedString(containerSet)).append("\n");
    sb.append("    daemon: ").append(toIndentedString(daemon)).append("\n");
    sb.append("    dag: ").append(toIndentedString(dag)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    executor: ").append(toIndentedString(executor)).append("\n");
    sb.append("    failFast: ").append(toIndentedString(failFast)).append("\n");
    sb.append("    hostAliases: ").append(toIndentedString(hostAliases)).append("\n");
    sb.append("    http: ").append(toIndentedString(http)).append("\n");
    sb.append("    initContainers: ").append(toIndentedString(initContainers)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    memoize: ").append(toIndentedString(memoize)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nodeSelector: ").append(toIndentedString(nodeSelector)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    parallelism: ").append(toIndentedString(parallelism)).append("\n");
    sb.append("    plugin: ").append(toIndentedString(plugin)).append("\n");
    sb.append("    podSpecPatch: ").append(toIndentedString(podSpecPatch)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    priorityClassName: ").append(toIndentedString(priorityClassName)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    retryStrategy: ").append(toIndentedString(retryStrategy)).append("\n");
    sb.append("    schedulerName: ").append(toIndentedString(schedulerName)).append("\n");
    sb.append("    script: ").append(toIndentedString(script)).append("\n");
    sb.append("    securityContext: ").append(toIndentedString(securityContext)).append("\n");
    sb.append("    serviceAccountName: ").append(toIndentedString(serviceAccountName)).append("\n");
    sb.append("    sidecars: ").append(toIndentedString(sidecars)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    suspend: ").append(toIndentedString(suspend)).append("\n");
    sb.append("    synchronization: ").append(toIndentedString(synchronization)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    tolerations: ").append(toIndentedString(tolerations)).append("\n");
    sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("activeDeadlineSeconds");
    openapiFields.add("affinity");
    openapiFields.add("annotations");
    openapiFields.add("archiveLocation");
    openapiFields.add("automountServiceAccountToken");
    openapiFields.add("container");
    openapiFields.add("containerSet");
    openapiFields.add("daemon");
    openapiFields.add("dag");
    openapiFields.add("data");
    openapiFields.add("executor");
    openapiFields.add("failFast");
    openapiFields.add("hostAliases");
    openapiFields.add("http");
    openapiFields.add("initContainers");
    openapiFields.add("inputs");
    openapiFields.add("memoize");
    openapiFields.add("metadata");
    openapiFields.add("metrics");
    openapiFields.add("name");
    openapiFields.add("nodeSelector");
    openapiFields.add("outputs");
    openapiFields.add("parallelism");
    openapiFields.add("plugin");
    openapiFields.add("podSpecPatch");
    openapiFields.add("priority");
    openapiFields.add("priorityClassName");
    openapiFields.add("resource");
    openapiFields.add("retryStrategy");
    openapiFields.add("schedulerName");
    openapiFields.add("script");
    openapiFields.add("securityContext");
    openapiFields.add("serviceAccountName");
    openapiFields.add("sidecars");
    openapiFields.add("steps");
    openapiFields.add("suspend");
    openapiFields.add("synchronization");
    openapiFields.add("timeout");
    openapiFields.add("tolerations");
    openapiFields.add("volumes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IoArgoprojWorkflowV1alpha1Template
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IoArgoprojWorkflowV1alpha1Template.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IoArgoprojWorkflowV1alpha1Template is not found in the empty JSON string", IoArgoprojWorkflowV1alpha1Template.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IoArgoprojWorkflowV1alpha1Template.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IoArgoprojWorkflowV1alpha1Template` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("activeDeadlineSeconds") != null && !jsonObj.get("activeDeadlineSeconds").isJsonNull()) && !jsonObj.get("activeDeadlineSeconds").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `activeDeadlineSeconds` to be a primitive type in the JSON string but got `%s`", jsonObj.get("activeDeadlineSeconds").toString()));
      }
      // validate the optional field `affinity`
      if (jsonObj.get("affinity") != null && !jsonObj.get("affinity").isJsonNull()) {
        IoK8sApiCoreV1Affinity.validateJsonElement(jsonObj.get("affinity"));
      }
      // validate the optional field `archiveLocation`
      if (jsonObj.get("archiveLocation") != null && !jsonObj.get("archiveLocation").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1ArtifactLocation.validateJsonElement(jsonObj.get("archiveLocation"));
      }
      // validate the optional field `container`
      if (jsonObj.get("container") != null && !jsonObj.get("container").isJsonNull()) {
        IoK8sApiCoreV1Container.validateJsonElement(jsonObj.get("container"));
      }
      // validate the optional field `containerSet`
      if (jsonObj.get("containerSet") != null && !jsonObj.get("containerSet").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1ContainerSetTemplate.validateJsonElement(jsonObj.get("containerSet"));
      }
      // validate the optional field `dag`
      if (jsonObj.get("dag") != null && !jsonObj.get("dag").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1DAGTemplate.validateJsonElement(jsonObj.get("dag"));
      }
      // validate the optional field `data`
      if (jsonObj.get("data") != null && !jsonObj.get("data").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1Data.validateJsonElement(jsonObj.get("data"));
      }
      // validate the optional field `executor`
      if (jsonObj.get("executor") != null && !jsonObj.get("executor").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1ExecutorConfig.validateJsonElement(jsonObj.get("executor"));
      }
      if (jsonObj.get("hostAliases") != null && !jsonObj.get("hostAliases").isJsonNull()) {
        JsonArray jsonArrayhostAliases = jsonObj.getAsJsonArray("hostAliases");
        if (jsonArrayhostAliases != null) {
          // ensure the json data is an array
          if (!jsonObj.get("hostAliases").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `hostAliases` to be an array in the JSON string but got `%s`", jsonObj.get("hostAliases").toString()));
          }

          // validate the optional field `hostAliases` (array)
          for (int i = 0; i < jsonArrayhostAliases.size(); i++) {
            IoK8sApiCoreV1HostAlias.validateJsonElement(jsonArrayhostAliases.get(i));
          };
        }
      }
      // validate the optional field `http`
      if (jsonObj.get("http") != null && !jsonObj.get("http").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1HTTP.validateJsonElement(jsonObj.get("http"));
      }
      if (jsonObj.get("initContainers") != null && !jsonObj.get("initContainers").isJsonNull()) {
        JsonArray jsonArrayinitContainers = jsonObj.getAsJsonArray("initContainers");
        if (jsonArrayinitContainers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("initContainers").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `initContainers` to be an array in the JSON string but got `%s`", jsonObj.get("initContainers").toString()));
          }

          // validate the optional field `initContainers` (array)
          for (int i = 0; i < jsonArrayinitContainers.size(); i++) {
            IoArgoprojWorkflowV1alpha1UserContainer.validateJsonElement(jsonArrayinitContainers.get(i));
          };
        }
      }
      // validate the optional field `inputs`
      if (jsonObj.get("inputs") != null && !jsonObj.get("inputs").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1Inputs.validateJsonElement(jsonObj.get("inputs"));
      }
      // validate the optional field `memoize`
      if (jsonObj.get("memoize") != null && !jsonObj.get("memoize").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1Memoize.validateJsonElement(jsonObj.get("memoize"));
      }
      // validate the optional field `metadata`
      if (jsonObj.get("metadata") != null && !jsonObj.get("metadata").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1Metadata.validateJsonElement(jsonObj.get("metadata"));
      }
      // validate the optional field `metrics`
      if (jsonObj.get("metrics") != null && !jsonObj.get("metrics").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1Metrics.validateJsonElement(jsonObj.get("metrics"));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `outputs`
      if (jsonObj.get("outputs") != null && !jsonObj.get("outputs").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1Outputs.validateJsonElement(jsonObj.get("outputs"));
      }
      if ((jsonObj.get("podSpecPatch") != null && !jsonObj.get("podSpecPatch").isJsonNull()) && !jsonObj.get("podSpecPatch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `podSpecPatch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("podSpecPatch").toString()));
      }
      if ((jsonObj.get("priorityClassName") != null && !jsonObj.get("priorityClassName").isJsonNull()) && !jsonObj.get("priorityClassName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `priorityClassName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("priorityClassName").toString()));
      }
      // validate the optional field `resource`
      if (jsonObj.get("resource") != null && !jsonObj.get("resource").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1ResourceTemplate.validateJsonElement(jsonObj.get("resource"));
      }
      // validate the optional field `retryStrategy`
      if (jsonObj.get("retryStrategy") != null && !jsonObj.get("retryStrategy").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1RetryStrategy.validateJsonElement(jsonObj.get("retryStrategy"));
      }
      if ((jsonObj.get("schedulerName") != null && !jsonObj.get("schedulerName").isJsonNull()) && !jsonObj.get("schedulerName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `schedulerName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("schedulerName").toString()));
      }
      // validate the optional field `script`
      if (jsonObj.get("script") != null && !jsonObj.get("script").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1ScriptTemplate.validateJsonElement(jsonObj.get("script"));
      }
      // validate the optional field `securityContext`
      if (jsonObj.get("securityContext") != null && !jsonObj.get("securityContext").isJsonNull()) {
        IoK8sApiCoreV1PodSecurityContext.validateJsonElement(jsonObj.get("securityContext"));
      }
      if ((jsonObj.get("serviceAccountName") != null && !jsonObj.get("serviceAccountName").isJsonNull()) && !jsonObj.get("serviceAccountName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serviceAccountName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serviceAccountName").toString()));
      }
      if (jsonObj.get("sidecars") != null && !jsonObj.get("sidecars").isJsonNull()) {
        JsonArray jsonArraysidecars = jsonObj.getAsJsonArray("sidecars");
        if (jsonArraysidecars != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sidecars").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sidecars` to be an array in the JSON string but got `%s`", jsonObj.get("sidecars").toString()));
          }

          // validate the optional field `sidecars` (array)
          for (int i = 0; i < jsonArraysidecars.size(); i++) {
            IoArgoprojWorkflowV1alpha1UserContainer.validateJsonElement(jsonArraysidecars.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("steps") != null && !jsonObj.get("steps").isJsonNull() && !jsonObj.get("steps").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `steps` to be an array in the JSON string but got `%s`", jsonObj.get("steps").toString()));
      }
      // validate the optional field `suspend`
      if (jsonObj.get("suspend") != null && !jsonObj.get("suspend").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1SuspendTemplate.validateJsonElement(jsonObj.get("suspend"));
      }
      // validate the optional field `synchronization`
      if (jsonObj.get("synchronization") != null && !jsonObj.get("synchronization").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1Synchronization.validateJsonElement(jsonObj.get("synchronization"));
      }
      if ((jsonObj.get("timeout") != null && !jsonObj.get("timeout").isJsonNull()) && !jsonObj.get("timeout").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timeout` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timeout").toString()));
      }
      if (jsonObj.get("tolerations") != null && !jsonObj.get("tolerations").isJsonNull()) {
        JsonArray jsonArraytolerations = jsonObj.getAsJsonArray("tolerations");
        if (jsonArraytolerations != null) {
          // ensure the json data is an array
          if (!jsonObj.get("tolerations").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `tolerations` to be an array in the JSON string but got `%s`", jsonObj.get("tolerations").toString()));
          }

          // validate the optional field `tolerations` (array)
          for (int i = 0; i < jsonArraytolerations.size(); i++) {
            IoK8sApiCoreV1Toleration.validateJsonElement(jsonArraytolerations.get(i));
          };
        }
      }
      if (jsonObj.get("volumes") != null && !jsonObj.get("volumes").isJsonNull()) {
        JsonArray jsonArrayvolumes = jsonObj.getAsJsonArray("volumes");
        if (jsonArrayvolumes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("volumes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `volumes` to be an array in the JSON string but got `%s`", jsonObj.get("volumes").toString()));
          }

          // validate the optional field `volumes` (array)
          for (int i = 0; i < jsonArrayvolumes.size(); i++) {
            IoK8sApiCoreV1Volume.validateJsonElement(jsonArrayvolumes.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IoArgoprojWorkflowV1alpha1Template.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IoArgoprojWorkflowV1alpha1Template' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IoArgoprojWorkflowV1alpha1Template> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IoArgoprojWorkflowV1alpha1Template.class));

       return (TypeAdapter<T>) new TypeAdapter<IoArgoprojWorkflowV1alpha1Template>() {
           @Override
           public void write(JsonWriter out, IoArgoprojWorkflowV1alpha1Template value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IoArgoprojWorkflowV1alpha1Template read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IoArgoprojWorkflowV1alpha1Template given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IoArgoprojWorkflowV1alpha1Template
   * @throws IOException if the JSON string is invalid with respect to IoArgoprojWorkflowV1alpha1Template
   */
  public static IoArgoprojWorkflowV1alpha1Template fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IoArgoprojWorkflowV1alpha1Template.class);
  }

  /**
   * Convert an instance of IoArgoprojWorkflowV1alpha1Template to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

