/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IoArgoprojEventsV1alpha1BitbucketBasicAuth;
import org.openapitools.client.model.IoK8sApiCoreV1SecretKeySelector;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * IoArgoprojEventsV1alpha1BitbucketAuth
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-24T03:51:41.763920791Z[Etc/UTC]", comments = "Generator version: 7.12.0-SNAPSHOT")
public class IoArgoprojEventsV1alpha1BitbucketAuth {
  public static final String SERIALIZED_NAME_BASIC = "basic";
  @SerializedName(SERIALIZED_NAME_BASIC)
  @javax.annotation.Nullable
  private IoArgoprojEventsV1alpha1BitbucketBasicAuth basic;

  public static final String SERIALIZED_NAME_OAUTH_TOKEN = "oauthToken";
  @SerializedName(SERIALIZED_NAME_OAUTH_TOKEN)
  @javax.annotation.Nullable
  private IoK8sApiCoreV1SecretKeySelector oauthToken;

  public IoArgoprojEventsV1alpha1BitbucketAuth() {
  }

  public IoArgoprojEventsV1alpha1BitbucketAuth basic(@javax.annotation.Nullable IoArgoprojEventsV1alpha1BitbucketBasicAuth basic) {
    this.basic = basic;
    return this;
  }

  /**
   * Get basic
   * @return basic
   */
  @javax.annotation.Nullable
  public IoArgoprojEventsV1alpha1BitbucketBasicAuth getBasic() {
    return basic;
  }

  public void setBasic(@javax.annotation.Nullable IoArgoprojEventsV1alpha1BitbucketBasicAuth basic) {
    this.basic = basic;
  }


  public IoArgoprojEventsV1alpha1BitbucketAuth oauthToken(@javax.annotation.Nullable IoK8sApiCoreV1SecretKeySelector oauthToken) {
    this.oauthToken = oauthToken;
    return this;
  }

  /**
   * Get oauthToken
   * @return oauthToken
   */
  @javax.annotation.Nullable
  public IoK8sApiCoreV1SecretKeySelector getOauthToken() {
    return oauthToken;
  }

  public void setOauthToken(@javax.annotation.Nullable IoK8sApiCoreV1SecretKeySelector oauthToken) {
    this.oauthToken = oauthToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojEventsV1alpha1BitbucketAuth ioArgoprojEventsV1alpha1BitbucketAuth = (IoArgoprojEventsV1alpha1BitbucketAuth) o;
    return Objects.equals(this.basic, ioArgoprojEventsV1alpha1BitbucketAuth.basic) &&
        Objects.equals(this.oauthToken, ioArgoprojEventsV1alpha1BitbucketAuth.oauthToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basic, oauthToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojEventsV1alpha1BitbucketAuth {\n");
    sb.append("    basic: ").append(toIndentedString(basic)).append("\n");
    sb.append("    oauthToken: ").append(toIndentedString(oauthToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("basic");
    openapiFields.add("oauthToken");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IoArgoprojEventsV1alpha1BitbucketAuth
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IoArgoprojEventsV1alpha1BitbucketAuth.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IoArgoprojEventsV1alpha1BitbucketAuth is not found in the empty JSON string", IoArgoprojEventsV1alpha1BitbucketAuth.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IoArgoprojEventsV1alpha1BitbucketAuth.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IoArgoprojEventsV1alpha1BitbucketAuth` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `basic`
      if (jsonObj.get("basic") != null && !jsonObj.get("basic").isJsonNull()) {
        IoArgoprojEventsV1alpha1BitbucketBasicAuth.validateJsonElement(jsonObj.get("basic"));
      }
      // validate the optional field `oauthToken`
      if (jsonObj.get("oauthToken") != null && !jsonObj.get("oauthToken").isJsonNull()) {
        IoK8sApiCoreV1SecretKeySelector.validateJsonElement(jsonObj.get("oauthToken"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IoArgoprojEventsV1alpha1BitbucketAuth.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IoArgoprojEventsV1alpha1BitbucketAuth' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IoArgoprojEventsV1alpha1BitbucketAuth> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IoArgoprojEventsV1alpha1BitbucketAuth.class));

       return (TypeAdapter<T>) new TypeAdapter<IoArgoprojEventsV1alpha1BitbucketAuth>() {
           @Override
           public void write(JsonWriter out, IoArgoprojEventsV1alpha1BitbucketAuth value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IoArgoprojEventsV1alpha1BitbucketAuth read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IoArgoprojEventsV1alpha1BitbucketAuth given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IoArgoprojEventsV1alpha1BitbucketAuth
   * @throws IOException if the JSON string is invalid with respect to IoArgoprojEventsV1alpha1BitbucketAuth
   */
  public static IoArgoprojEventsV1alpha1BitbucketAuth fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IoArgoprojEventsV1alpha1BitbucketAuth.class);
  }

  /**
   * Convert an instance of IoArgoprojEventsV1alpha1BitbucketAuth to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

