/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GrpcGatewayRuntimeStreamError;
import org.openapitools.client.model.IoArgoprojWorkflowV1alpha1WorkflowWatchEvent;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-24T03:51:41.763920791Z[Etc/UTC]", comments = "Generator version: 7.12.0-SNAPSHOT")
public class StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent {
  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  @javax.annotation.Nullable
  private GrpcGatewayRuntimeStreamError error;

  public static final String SERIALIZED_NAME_RESULT = "result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  @javax.annotation.Nullable
  private IoArgoprojWorkflowV1alpha1WorkflowWatchEvent result;

  public StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent() {
  }

  public StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent error(@javax.annotation.Nullable GrpcGatewayRuntimeStreamError error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  public GrpcGatewayRuntimeStreamError getError() {
    return error;
  }

  public void setError(@javax.annotation.Nullable GrpcGatewayRuntimeStreamError error) {
    this.error = error;
  }


  public StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent result(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1WorkflowWatchEvent result) {
    this.result = result;
    return this;
  }

  /**
   * Get result
   * @return result
   */
  @javax.annotation.Nullable
  public IoArgoprojWorkflowV1alpha1WorkflowWatchEvent getResult() {
    return result;
  }

  public void setResult(@javax.annotation.Nullable IoArgoprojWorkflowV1alpha1WorkflowWatchEvent result) {
    this.result = result;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent streamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent = (StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent) o;
    return Objects.equals(this.error, streamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent.error) &&
        Objects.equals(this.result, streamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, result);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent {\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("error");
    openapiFields.add("result");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent is not found in the empty JSON string", StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `error`
      if (jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) {
        GrpcGatewayRuntimeStreamError.validateJsonElement(jsonObj.get("error"));
      }
      // validate the optional field `result`
      if (jsonObj.get("result") != null && !jsonObj.get("result").isJsonNull()) {
        IoArgoprojWorkflowV1alpha1WorkflowWatchEvent.validateJsonElement(jsonObj.get("result"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent.class));

       return (TypeAdapter<T>) new TypeAdapter<StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent>() {
           @Override
           public void write(JsonWriter out, StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent
   * @throws IOException if the JSON string is invalid with respect to StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent
   */
  public static StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent.class);
  }

  /**
   * Convert an instance of StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

